# Generated by Django 4.2.3 on 2023-07-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornada_milhas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depoimento',
            old_name='Depoimento',
            new_name='depoimento',
        ),
    ]
