# Generated by Django 4.2.3 on 2023-07-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada_milhas', '0002_rename_depoimento_depoimento_depoimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='setup/assets/galeria_destinos')),
                ('nome', models.CharField(max_length=100)),
                ('preço', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='foto',
            field=models.ImageField(upload_to='setup/assets/galeria_users'),
        ),
    ]
