# Generated by Django 4.2.3 on 2023-07-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada_milhas', '0003_destino_alter_depoimento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimento',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='destino',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
