# Generated by Django 4.2.3 on 2023-07-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada_milhas', '0004_alter_depoimento_foto_alter_destino_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destino',
            old_name='foto',
            new_name='foto_principal',
        ),
        migrations.AddField(
            model_name='destino',
            name='foto_secundaria',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='destino',
            name='meta',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
