# Generated by Django 4.2.3 on 2023-07-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada_milhas', '0005_rename_foto_destino_foto_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='texto_descritivo',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
