# Generated by Django 4.2.3 on 2023-07-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada_milhas', '0006_destino_texto_descritivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='texto_descritivo',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
